name: todo_app_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  introduction_screen: ^4.0.0
  provider: ^6.1.5+1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
